"""
Django settings for UMT project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-9ju!en2%3@bw-+_=(a5_!o0a_6_)wfmbgt$c92d)*@v1r&ddw@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']  # Cho phép mọi địa chỉ truy cập


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'umt_youth_union',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # <-- Dòng này để chạy web trên mạng (đặt ngay sau Security)
    'django.contrib.sessions.middleware.SessionMiddleware', # Bắt buộc (Quản lý phiên làm việc)
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware', # Bắt buộc (Quản lý đăng nhập)
    'django.contrib.messages.middleware.MessageMiddleware',    # Bắt buộc (Quản lý thông báo/cái chuông)
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'UMT.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'umt_youth_union.context_processors.thong_bao_chung',
            ],
        },
    },
]

WSGI_APPLICATION = 'UMT.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# settings.py

STATIC_URL = 'static/'

# Thêm dòng này nếu chưa có để đảm bảo Django tìm đúng chỗ
import os
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'umt_youth_union/static'),
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
import os

# Cấu hình đường dẫn lưu ảnh/file
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# Cấu hình gửi mail thật qua Gmail
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'phuchuynh140706@gmail.com' # ⚠️ Thay bằng Gmail của bạn
EMAIL_HOST_PASSWORD = 'ygzw twit nygl zcmk' # Cấu hình gửi mail thật qua Gmail
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'phuchuynh140706@gmail.com' # ⚠️ Thay bằng Gmail của bạn
EMAIL_HOST_PASSWORD = 'ygzw twit nygl zcmk' 
import os

# ... các code cũ giữ nguyên ...

# Cấu hình đường dẫn file Tĩnh (CSS/JS)
STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'umt_youth_union/static')]

# 🌟 CẤU HÌNH MEDIA (QUAN TRỌNG ĐỂ LƯU ẢNH)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')# ⚠️ Thay bằng Mật khẩu ứng dụng 16 ký tự # ⚠️ Thay bằng Mật khẩu ứng dụng 16 ký tự
# Cấu hình tin tưởng địa chỉ của Ngrok (Cho phép https)
CSRF_TRUSTED_ORIGINS = [
    'https://*.ngrok-free.app',
]
import os
import dj_database_url # Import cái này

# 1. Cho phép mọi nơi truy cập
ALLOWED_HOSTS = ['*']

# 3. Cấu hình Database tự động (Local dùng SQLite/XAMPP, lên mạng dùng Cloud)
# Xóa đoạn DATABASES cũ đi, thay bằng đoạn này:
DATABASES = {
    'default': dj_database_url.config(
        # Nếu không tìm thấy DB onlines, nó sẽ dùng tạm SQLite ở máy để không bị lỗi code
        default='sqlite:///db.sqlite3', 
        conn_max_age=600
    )
}

# 4. Cấu hình nén file tĩnh
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
# settings.py
DATABASES = {
    'default': dj_database_url.config(
        default='postgresql://postgres.hrczlhcvuwqdrfqpdjpk:phuchuynh1407@aws-1-ap-northeast-1.pooler.supabase.com:6543/postgres',
        conn_max_age=600
    )
}