# Generated by Django 5.2.8 on 2025-11-30 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SinhVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_sinh_vien', models.CharField(max_length=15, unique=True)),
                ('ho_ten', models.CharField(max_length=100)),
                ('khoa_vien', models.CharField(max_length=50)),
                ('lop', models.CharField(max_length=20)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HoSoSinhVien5Tot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nam_hoc', models.CharField(max_length=9)),
                ('dao_duc_tot', models.BooleanField(default=False)),
                ('hoc_tap_tot', models.BooleanField(default=False)),
                ('the_luc_tot', models.BooleanField(default=False)),
                ('tinh_nguyen_tot', models.BooleanField(default=False)),
                ('hoi_nhap_tot', models.BooleanField(default=False)),
                ('trang_thai', models.CharField(choices=[('CHO_DUYET', 'Chờ Duyệt'), ('DAT', 'Đã Đạt'), ('KHONG_DAT', 'Không Đạt')], default='CHO_DUYET', max_length=20)),
                ('sinh_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='umt_youth_union.sinhvien')),
            ],
        ),
        migrations.CreateModel(
            name='VinhDanhCaNhan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('danh_hieu', models.CharField(max_length=100)),
                ('nam_dat', models.IntegerField()),
                ('thanh_tich', models.TextField()),
                ('sinh_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='umt_youth_union.sinhvien')),
            ],
        ),
    ]
