# Generated by Django 5.2.8 on 2025-11-30 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umt_youth_union', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuyDinhDieuLe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_van_ban', models.CharField(max_length=255)),
                ('loai_danh_hieu', models.CharField(max_length=100)),
                ('mo_ta', models.TextField(blank=True, null=True)),
                ('file_pdf', models.FileField(blank=True, null=True, upload_to='quyet_dinh/')),
                ('ngay_ban_hanh', models.DateField()),
            ],
            options={
                'verbose_name_plural': '4. Quy định & Điều lệ',
            },
        ),
    ]
