# Generated by Django 5.2.8 on 2025-11-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umt_youth_union', '0002_quydinhdieule'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinhvien',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Ảnh đại diện'),
        ),
    ]
