# Generated by Django 5.2.8 on 2025-11-30 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umt_youth_union', '0003_sinhvien_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sinhvien',
            name='lop',
        ),
        migrations.AddField(
            model_name='sinhvien',
            name='chi_doan',
            field=models.CharField(default='Chưa cập nhật', max_length=50, verbose_name='Chi Đoàn (Lớp)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sinhvien',
            name='chuc_vu',
            field=models.CharField(default='Đoàn viên', max_length=50, verbose_name='Chức vụ Đoàn'),
        ),
        migrations.AddField(
            model_name='sinhvien',
            name='dia_chi_tam_tru',
            field=models.TextField(blank=True, null=True, verbose_name='Nơi tạm trú'),
        ),
        migrations.AddField(
            model_name='sinhvien',
            name='dia_chi_thuong_tru',
            field=models.TextField(blank=True, null=True, verbose_name='Nơi thường trú'),
        ),
        migrations.AddField(
            model_name='sinhvien',
            name='email_sv',
            field=models.EmailField(default='Chưa cập nhật', max_length=100, verbose_name='Email Sinh viên'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sinhvien',
            name='khoa_hoc',
            field=models.CharField(default='Chưa cập nhật', max_length=20, verbose_name='Khóa (VD: K1, K2)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sinhvien',
            name='ngay_sinh',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày sinh'),
        ),
        migrations.AddField(
            model_name='sinhvien',
            name='quoc_tich',
            field=models.CharField(default='Việt Nam', max_length=50, verbose_name='Quốc tịch'),
        ),
        migrations.AddField(
            model_name='sinhvien',
            name='so_dien_thoai',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Số điện thoại'),
        ),
        migrations.AddField(
            model_name='sinhvien',
            name='truong',
            field=models.CharField(default='Đại học Quản lý và Công nghệ TP.HCM (UMT)', max_length=100, verbose_name='Trường'),
        ),
        migrations.AlterField(
            model_name='sinhvien',
            name='ho_ten',
            field=models.CharField(max_length=100, verbose_name='Họ và Tên'),
        ),
        migrations.AlterField(
            model_name='sinhvien',
            name='khoa_vien',
            field=models.CharField(max_length=100, verbose_name='Khoa/Viện'),
        ),
        migrations.AlterField(
            model_name='sinhvien',
            name='ma_sinh_vien',
            field=models.CharField(max_length=15, unique=True, verbose_name='MSSV'),
        ),
        migrations.AlterField(
            model_name='sinhvien',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
