# Generated by Django 5.2.8 on 2025-11-30 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umt_youth_union', '0004_remove_sinhvien_lop_sinhvien_chi_doan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChiDoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_chi_doan', models.CharField(max_length=50, unique=True, verbose_name='Tên Chi Đoàn')),
                ('khoa', models.CharField(max_length=100, verbose_name='Khoa/Viện')),
                ('khoa_hoc', models.CharField(max_length=20, verbose_name='Khóa')),
            ],
            options={
                'verbose_name_plural': '0. Danh sách Chi Đoàn',
            },
        ),
        migrations.AlterModelOptions(
            name='quydinhdieule',
            options={},
        ),
        migrations.RemoveField(
            model_name='sinhvien',
            name='chi_doan',
        ),
        migrations.RemoveField(
            model_name='sinhvien',
            name='khoa_hoc',
        ),
        migrations.RemoveField(
            model_name='sinhvien',
            name='khoa_vien',
        ),
        migrations.AlterField(
            model_name='sinhvien',
            name='chuc_vu',
            field=models.CharField(choices=[('DOAN_VIEN', 'Đoàn viên'), ('BI_THU', 'Bí thư Chi đoàn'), ('PHO_BI_THU', 'Phó Bí thư Chi đoàn'), ('UY_VIEN', 'Ủy viên BCH'), ('CTV', 'Cộng tác viên')], default='DOAN_VIEN', max_length=20, verbose_name='Chức vụ Đoàn'),
        ),
        migrations.AlterField(
            model_name='vinhdanhcanhan',
            name='danh_hieu',
            field=models.CharField(choices=[('CBTB', 'Cán bộ Đoàn Thanh niên Tiêu biểu'), ('DVUT', 'Đoàn viên Ưu tú'), ('TNTT', 'Thanh niên Tiên tiến làm theo lời Bác')], max_length=4),
        ),
        migrations.AddField(
            model_name='sinhvien',
            name='chi_doan_gan_ket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='umt_youth_union.chidoan', verbose_name='Chi Đoàn'),
        ),
    ]
