# Generated by Django 5.2.8 on 2025-11-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umt_youth_union', '0005_chidoan_alter_quydinhdieule_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chidoan',
            name='khoa_hoc',
        ),
        migrations.AddField(
            model_name='sinhvien',
            name='khoa_hoc',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Khóa học (VD: K01)'),
        ),
    ]
