# Generated by Django 5.2.8 on 2025-11-30 15:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umt_youth_union', '0006_remove_chidoan_khoa_hoc_sinhvien_khoa_hoc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vinhdanhcanhan',
            options={'verbose_name_plural': '3. Vinh danh & Khen thưởng'},
        ),
        migrations.RemoveField(
            model_name='vinhdanhcanhan',
            name='thanh_tich',
        ),
        migrations.AddField(
            model_name='vinhdanhcanhan',
            name='hinh_anh_vinh_danh',
            field=models.ImageField(blank=True, null=True, upload_to='vinh_danh/', verbose_name='Ảnh sự kiện (Ngang)'),
        ),
        migrations.AddField(
            model_name='vinhdanhcanhan',
            name='ngay_dang',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Ngày đăng'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vinhdanhcanhan',
            name='noi_dung_bai_viet',
            field=models.TextField(default='Nội dung đang cập nhật', verbose_name='Nội dung bài viết (Mô tả thành tích)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vinhdanhcanhan',
            name='tieu_de',
            field=models.CharField(default='Gương mặt tiêu biểu', max_length=200, verbose_name='Tiêu đề Vinh danh'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vinhdanhcanhan',
            name='danh_hieu',
            field=models.CharField(choices=[('CBTB', 'Cán bộ Đoàn Thanh niên Tiêu biểu'), ('DVUT', 'Đoàn viên Ưu tú'), ('TNTT', 'Thanh niên Tiên tiến làm theo lời Bác'), ('KHEN', 'Giấy khen cấp Trường')], max_length=4, verbose_name='Danh hiệu'),
        ),
        migrations.AlterField(
            model_name='vinhdanhcanhan',
            name='nam_dat',
            field=models.IntegerField(verbose_name='Năm khen thưởng'),
        ),
        migrations.AlterField(
            model_name='vinhdanhcanhan',
            name='sinh_vien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='umt_youth_union.sinhvien', verbose_name='Sinh viên'),
        ),
    ]
