# Generated by Django 5.2.8 on 2025-11-30 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umt_youth_union', '0007_alter_vinhdanhcanhan_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vinhdanhcanhan',
            options={},
        ),
        migrations.AlterField(
            model_name='sinhvien',
            name='khoa_hoc',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Khóa học'),
        ),
        migrations.AlterField(
            model_name='vinhdanhcanhan',
            name='danh_hieu',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vinhdanhcanhan',
            name='hinh_anh_vinh_danh',
            field=models.ImageField(blank=True, null=True, upload_to='vinh_danh/'),
        ),
        migrations.AlterField(
            model_name='vinhdanhcanhan',
            name='nam_dat',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vinhdanhcanhan',
            name='ngay_dang',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vinhdanhcanhan',
            name='noi_dung_bai_viet',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vinhdanhcanhan',
            name='sinh_vien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='umt_youth_union.sinhvien'),
        ),
        migrations.AlterField(
            model_name='vinhdanhcanhan',
            name='tieu_de',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='HoSoXetDuyet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nam_hoc', models.CharField(max_length=9, verbose_name='Năm học (VD: 2024-2025)')),
                ('loai_danh_hieu', models.CharField(choices=[('SV5T', 'Sinh viên 5 Tốt'), ('TNTT', 'Thanh niên Tiên tiến làm theo lời Bác'), ('CBTB', 'Cán bộ Đoàn Tiêu biểu'), ('KHAC', 'Thành tích khác')], default='SV5T', max_length=10, verbose_name='Loại xét duyệt')),
                ('mo_ta_thanh_tich', models.TextField(verbose_name='Mô tả thành tích / Lý do xét duyệt')),
                ('trang_thai', models.CharField(choices=[('CHO_DUYET', 'Chờ Duyệt'), ('DAT', 'Đã Duyệt (Đạt)'), ('KHONG_DAT', 'Từ chối')], default='CHO_DUYET', max_length=20)),
                ('ngay_nop', models.DateField(auto_now_add=True)),
                ('sinh_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='umt_youth_union.sinhvien')),
            ],
        ),
        migrations.CreateModel(
            name='MinhChung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hinh_anh', models.ImageField(upload_to='minh_chung/', verbose_name='Ảnh minh chứng')),
                ('ho_so', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minh_chung_list', to='umt_youth_union.hosoxetduyet')),
            ],
        ),
        migrations.DeleteModel(
            name='HoSoSinhVien5Tot',
        ),
    ]
