# Generated by Django 5.2.8 on 2025-12-01 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umt_youth_union', '0008_alter_vinhdanhcanhan_options_alter_sinhvien_khoa_hoc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sinhvien',
            name='dia_chi_tam_tru',
        ),
        migrations.RemoveField(
            model_name='sinhvien',
            name='dia_chi_thuong_tru',
        ),
        migrations.RemoveField(
            model_name='sinhvien',
            name='email_sv',
        ),
        migrations.RemoveField(
            model_name='sinhvien',
            name='khoa_hoc',
        ),
        migrations.RemoveField(
            model_name='sinhvien',
            name='ngay_sinh',
        ),
        migrations.RemoveField(
            model_name='sinhvien',
            name='quoc_tich',
        ),
        migrations.RemoveField(
            model_name='sinhvien',
            name='so_dien_thoai',
        ),
        migrations.RemoveField(
            model_name='sinhvien',
            name='truong',
        ),
        migrations.AddField(
            model_name='hosoxetduyet',
            name='ly_do_tu_choi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hosoxetduyet',
            name='noi_dung_vinh_danh',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='minhchung',
            name='ghi_chu_loi',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ghi chú lỗi'),
        ),
        migrations.AddField(
            model_name='minhchung',
            name='is_valid',
            field=models.BooleanField(default=False, verbose_name='Hợp lệ'),
        ),
        migrations.AlterField(
            model_name='hosoxetduyet',
            name='loai_danh_hieu',
            field=models.CharField(choices=[('SV5T', 'Sinh viên 5 Tốt'), ('TNTT', 'TN Tiên tiến'), ('CBTB', 'Cán bộ Tiêu biểu')], default='SV5T', max_length=10),
        ),
        migrations.AlterField(
            model_name='hosoxetduyet',
            name='mo_ta_thanh_tich',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hosoxetduyet',
            name='nam_hoc',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='hosoxetduyet',
            name='trang_thai',
            field=models.CharField(choices=[('CHO_MINH_CHUNG', 'Chờ Ủy viên duyệt MC'), ('CHO_KHOA', 'Chờ Khoa duyệt'), ('CHO_TRUONG', 'Chờ Trường duyệt'), ('DAT', 'Đã Duyệt (Vinh danh)'), ('TU_CHOI', 'Đã từ chối')], default='CHO_MINH_CHUNG', max_length=20),
        ),
        migrations.AlterField(
            model_name='minhchung',
            name='hinh_anh',
            field=models.ImageField(upload_to='minh_chung/'),
        ),
        migrations.AlterField(
            model_name='sinhvien',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='sinhvien',
            name='chi_doan_gan_ket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='umt_youth_union.chidoan'),
        ),
        migrations.AlterField(
            model_name='sinhvien',
            name='chuc_vu',
            field=models.CharField(choices=[('DOAN_VIEN', 'Đoàn viên'), ('UY_VIEN', 'Ủy viên (Duyệt Minh chứng)'), ('BI_THU_KHOA', 'Bí thư Khoa (Duyệt cấp 1)'), ('BI_THU_TRUONG', 'Bí thư Trường (Duyệt cuối)')], default='DOAN_VIEN', max_length=20),
        ),
        migrations.AlterField(
            model_name='sinhvien',
            name='ho_ten',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sinhvien',
            name='ma_sinh_vien',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
