# Generated by Django 5.2.8 on 2025-12-01 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umt_youth_union', '0009_remove_sinhvien_dia_chi_tam_tru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minhchung',
            name='ghi_chu_loi',
        ),
        migrations.AddField(
            model_name='sinhvien',
            name='dia_chi_tam_tru',
            field=models.TextField(blank=True, null=True, verbose_name='Nơi tạm trú'),
        ),
        migrations.AddField(
            model_name='sinhvien',
            name='dia_chi_thuong_tru',
            field=models.TextField(blank=True, null=True, verbose_name='Nơi thường trú'),
        ),
        migrations.AddField(
            model_name='sinhvien',
            name='email_sv',
            field=models.EmailField(default='update@umt.edu.vn', max_length=100, verbose_name='Email Sinh viên'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sinhvien',
            name='khoa_hoc',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Khóa học'),
        ),
        migrations.AddField(
            model_name='sinhvien',
            name='ngay_sinh',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày sinh'),
        ),
        migrations.AddField(
            model_name='sinhvien',
            name='quoc_tich',
            field=models.CharField(default='Việt Nam', max_length=50, verbose_name='Quốc tịch'),
        ),
        migrations.AddField(
            model_name='sinhvien',
            name='so_dien_thoai',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Số điện thoại'),
        ),
        migrations.AddField(
            model_name='sinhvien',
            name='truong',
            field=models.CharField(default='Đại học Quản lý và Công nghệ TP.HCM (UMT)', max_length=100, verbose_name='Trường'),
        ),
        migrations.AlterField(
            model_name='hosoxetduyet',
            name='loai_danh_hieu',
            field=models.CharField(choices=[('SV5T', 'Sinh viên 5 Tốt'), ('TNTT', 'Thanh niên Tiên tiến làm theo lời Bác'), ('CBTB', 'Cán bộ Đoàn Tiêu biểu'), ('KHAC', 'Thành tích khác')], default='SV5T', max_length=10, verbose_name='Loại danh hiệu'),
        ),
        migrations.AlterField(
            model_name='hosoxetduyet',
            name='mo_ta_thanh_tich',
            field=models.TextField(verbose_name='Mô tả thành tích'),
        ),
        migrations.AlterField(
            model_name='hosoxetduyet',
            name='nam_hoc',
            field=models.CharField(max_length=9, verbose_name='Năm học'),
        ),
        migrations.AlterField(
            model_name='hosoxetduyet',
            name='noi_dung_vinh_danh',
            field=models.TextField(blank=True, null=True, verbose_name='Bài viết Vinh danh'),
        ),
        migrations.AlterField(
            model_name='minhchung',
            name='hinh_anh',
            field=models.ImageField(upload_to='minh_chung/', verbose_name='Ảnh minh chứng'),
        ),
        migrations.AlterField(
            model_name='sinhvien',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Ảnh đại diện'),
        ),
        migrations.AlterField(
            model_name='sinhvien',
            name='chi_doan_gan_ket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='umt_youth_union.chidoan', verbose_name='Chi Đoàn'),
        ),
        migrations.AlterField(
            model_name='sinhvien',
            name='chuc_vu',
            field=models.CharField(choices=[('DOAN_VIEN', 'Đoàn viên (Nộp hồ sơ)'), ('UY_VIEN', 'Ủy viên (Duyệt Minh chứng)'), ('BI_THU_KHOA', 'Bí thư Khoa (Duyệt cấp 1)'), ('BI_THU_TRUONG', 'Bí thư Trường (Duyệt cuối)')], default='DOAN_VIEN', max_length=20, verbose_name='Chức vụ Đoàn'),
        ),
        migrations.AlterField(
            model_name='sinhvien',
            name='ho_ten',
            field=models.CharField(max_length=100, verbose_name='Họ và Tên'),
        ),
        migrations.AlterField(
            model_name='sinhvien',
            name='ma_sinh_vien',
            field=models.CharField(max_length=15, unique=True, verbose_name='MSSV'),
        ),
    ]
